### ISSUE TITLE
How can I get a test image?

### ISSUE THREAD

**Issue by fiona-lxd** [lyangas/depthmap_from_jpeg#2]
This code works fine with your provided test image. However, when I replaced it with my self-portrait photo which is taken under the portrait mode of my iPhone 13, this code always gets error like this: 
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    ios_image = IOSImage('test.jpeg')
  File "test.py", line 21, in __init__
    self.depthmap = self.layers[2]
IndexError: list index out of range

Please do help me out. Thanks in advance.

**Comment by lyangas** [comment]
Now i have uploaded photo from iphone 13 and it uploaded successfully. Probably the photo you used is "rendered jpeg" with no additional information like a depth map. This happens if it is not correct to transfer a photo from an iPhone to a computer.

I am using mac os and my order is like this:

1) take a photo

2) on the phone select "share" -> airdrop

3) I transfer the photo to my mac, it appears in the downloads - I use this file

if you just drag a photo from the "photo" application on mac os, then the resulting .JPG file will not have the necessary data (depth map)

**Comment by fiona-lxd** [comment]
Thank you so much for your help. Following your instructions, I have already made it with airdrop and iCloud. It is because I used another app for transferring my photo before. This caused loss of the depth information. Again, thank you a lot.

**Comment by lyangas** [comment]
@fiona-lxd I am glad to help :)
